const POST_PRODUCT = "POST_PRODUCT";
const NEW_PRODUCT = "NEW_PRODUCT";
const UPDATE_PRODUCT = "UPDATE_PRODUCT";
const POST_MESSAGE = "POST_MESSAGE";
const NEW_MESSAGE = "NEW_MESSAGE";
const UPDATE_MESSAGE = "UPDATE_MESSAGE";

module.exports = {
    POST_PRODUCT,
    NEW_PRODUCT,
    UPDATE_PRODUCT,
    POST_MESSAGE,
    NEW_MESSAGE,
    UPDATE_MESSAGE
}