const POST_MESSAGE = "POST_MESSAGE";
const NEW_MESSAGE = "NEW_MESSAGE";
const UPDATE_MESSAGE = "UPDATE_MESSAGE";
const LIKE_MESSAGE = "LIKE_MESSAGE";

module.exports = {
    POST_MESSAGE,
    NEW_MESSAGE,
    UPDATE_MESSAGE,
    LIKE_MESSAGE
}